// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
  name,
  description,
  genre,
  tone,
  themes,
  world_type,
  danger_level,
  political_complexity,
  status,
  created_by
) VALUES (
  $1,
  $2,
  $3,
  $4,
  COALESCE($5::text[], '{}'::text[]),
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, name, description, genre, tone, themes, status, created_by, created_at, updated_at, world_type, danger_level, political_complexity
`

type CreateCampaignParams struct {
	Name                string
	Description         pgtype.Text
	Genre               pgtype.Text
	Tone                pgtype.Text
	Themes              []string
	WorldType           pgtype.Text
	DangerLevel         pgtype.Text
	PoliticalComplexity pgtype.Text
	Status              string
	CreatedBy           pgtype.UUID
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.Description,
		arg.Genre,
		arg.Tone,
		arg.Themes,
		arg.WorldType,
		arg.DangerLevel,
		arg.PoliticalComplexity,
		arg.Status,
		arg.CreatedBy,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorldType,
		&i.DangerLevel,
		&i.PoliticalComplexity,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, description, genre, tone, themes, status, created_by, created_at, updated_at, world_type, danger_level, political_complexity
FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorldType,
		&i.DangerLevel,
		&i.PoliticalComplexity,
	)
	return i, err
}

const listCampaignsByUser = `-- name: ListCampaignsByUser :many
SELECT id, name, description, genre, tone, themes, status, created_by, created_at, updated_at, world_type, danger_level, political_complexity
FROM campaigns
WHERE created_by = $1
ORDER BY created_at, id
`

func (q *Queries) ListCampaignsByUser(ctx context.Context, createdBy pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Genre,
			&i.Tone,
			&i.Themes,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorldType,
			&i.DangerLevel,
			&i.PoliticalComplexity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
  name = $1,
  description = $2,
  genre = $3,
  tone = $4,
  themes = COALESCE($5::text[], '{}'::text[]),
  world_type = $6,
  danger_level = $7,
  political_complexity = $8,
  updated_at = now()
WHERE id = $9
RETURNING id, name, description, genre, tone, themes, status, created_by, created_at, updated_at, world_type, danger_level, political_complexity
`

type UpdateCampaignParams struct {
	Name                string
	Description         pgtype.Text
	Genre               pgtype.Text
	Tone                pgtype.Text
	Themes              []string
	WorldType           pgtype.Text
	DangerLevel         pgtype.Text
	PoliticalComplexity pgtype.Text
	ID                  pgtype.UUID
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Description,
		arg.Genre,
		arg.Tone,
		arg.Themes,
		arg.WorldType,
		arg.DangerLevel,
		arg.PoliticalComplexity,
		arg.ID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorldType,
		&i.DangerLevel,
		&i.PoliticalComplexity,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET
  status = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, name, description, genre, tone, themes, status, created_by, created_at, updated_at, world_type, danger_level, political_complexity
`

type UpdateCampaignStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.Status, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Genre,
		&i.Tone,
		&i.Themes,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorldType,
		&i.DangerLevel,
		&i.PoliticalComplexity,
	)
	return i, err
}
