// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreatePlayerCharacter(ctx context.Context, arg CreatePlayerCharacterParams) (PlayerCharacter, error)
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteCampaign(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetPlayerCharacterByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]PlayerCharacter, error)
	GetPlayerCharacterByID(ctx context.Context, id pgtype.UUID) (PlayerCharacter, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	ListCampaignsByUser(ctx context.Context, createdBy pgtype.UUID) ([]Campaign, error)
	ListUsers(ctx context.Context) ([]User, error)
	Ping(ctx context.Context) (int32, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdatePlayerCharacter(ctx context.Context, arg UpdatePlayerCharacterParams) (PlayerCharacter, error)
	UpdatePlayerExperience(ctx context.Context, arg UpdatePlayerExperienceParams) (PlayerCharacter, error)
	UpdatePlayerHP(ctx context.Context, arg UpdatePlayerHPParams) (PlayerCharacter, error)
	UpdatePlayerLocation(ctx context.Context, arg UpdatePlayerLocationParams) (PlayerCharacter, error)
	UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (PlayerCharacter, error)
	UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) (PlayerCharacter, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
