// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quest_notes.sql

package statedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestHistoryEntry = `-- name: CreateQuestHistoryEntry :one
INSERT INTO quest_history (quest_id, snapshot)
VALUES ($1, $2)
RETURNING id, quest_id, snapshot, created_at
`

type CreateQuestHistoryEntryParams struct {
	QuestID  pgtype.UUID
	Snapshot string
}

func (q *Queries) CreateQuestHistoryEntry(ctx context.Context, arg CreateQuestHistoryEntryParams) (QuestHistory, error) {
	row := q.db.QueryRow(ctx, createQuestHistoryEntry, arg.QuestID, arg.Snapshot)
	var i QuestHistory
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestNote = `-- name: CreateQuestNote :one
INSERT INTO quest_notes (quest_id, content)
VALUES ($1, $2)
RETURNING id, quest_id, content, created_at, updated_at
`

type CreateQuestNoteParams struct {
	QuestID pgtype.UUID
	Content string
}

func (q *Queries) CreateQuestNote(ctx context.Context, arg CreateQuestNoteParams) (QuestNote, error) {
	row := q.db.QueryRow(ctx, createQuestNote, arg.QuestID, arg.Content)
	var i QuestNote
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestNote = `-- name: DeleteQuestNote :exec
DELETE FROM quest_notes
WHERE id = $1 AND quest_id = $2
`

type DeleteQuestNoteParams struct {
	ID      pgtype.UUID
	QuestID pgtype.UUID
}

func (q *Queries) DeleteQuestNote(ctx context.Context, arg DeleteQuestNoteParams) error {
	_, err := q.db.Exec(ctx, deleteQuestNote, arg.ID, arg.QuestID)
	return err
}

const listQuestHistory = `-- name: ListQuestHistory :many
SELECT id, quest_id, snapshot, created_at
FROM quest_history
WHERE quest_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListQuestHistory(ctx context.Context, questID pgtype.UUID) ([]QuestHistory, error) {
	rows, err := q.db.Query(ctx, listQuestHistory, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestHistory
	for rows.Next() {
		var i QuestHistory
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestNotes = `-- name: ListQuestNotes :many
SELECT id, quest_id, content, created_at, updated_at
FROM quest_notes
WHERE quest_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListQuestNotes(ctx context.Context, questID pgtype.UUID) ([]QuestNote, error) {
	rows, err := q.db.Query(ctx, listQuestNotes, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestNote
	for rows.Next() {
		var i QuestNote
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
